build:
  image: google/dart:$$DART_VERSION
  pull: true
  commands:
    - sh build.sh
  environment:
    - COVERALLS_TOKEN=$$COVERALLS_TOKEN
matrix:
  DART_VERSION:
    - latest
    - "1.13.0-dev.1.0"
