// Generated by Dogma Dart. DO NOT MODIFY!
// 2015-09-26 21:53:16.401



library dogma_codegen;

//---------------------------------------------------------------------
// Library contents
//---------------------------------------------------------------------

enum ColorImplicit { red, green, blue, }
